--DROP DATABASE DB--
DROP DATABASE IF EXISTS DB;

--CREATE DATABASE DB--
IF NOT EXISTS(SELECT NAME FROM SYS.DATABASES WHERE NAME='DB')
BEGIN
	CREATE DATABASE DB;
END;

--USE DATABASE DB--
USE DB;

--DROP TABLE IF EXISTS--
DROP TABLE IF EXISTS Employees;

--CREATE EMPLOYEES TABLE--
CREATE TABLE Employees(EmpId INT PRIMARY KEY,
EmpName VARCHAR(50) NOT NULL,
EmpAge INT,
Salary MONEY);

--SELECT ALL FROM EMPLOYEES--
SELECT * FROM Employees;

--INSERT VALUES INTO EMPLOYEES--
INSERT INTO Employees(EmpId,EmpName,EmpAge,Salary)
VALUES(1000, 'Julius',45,340000),
(1001,'Helvine',30,132500),
(1002,'Amos',39,450000),
(1003,'Faith',23,560045),
(1004,'Enock',42,1500000);

--LIKE WHERE NAME LIKE 'F%'--
SELECT * FROM Employees WHERE EmpName LIKE 'F%';

--UPDATE--
UPDATE Employees
SET Salary=35600
WHERE EmpId=1001;

UPDATE Employees
SET EmpAge=45,Salary=356000
WHERE EmpId=1001;

--CREATE EMP TABLE--
--DROP IF IT EXISTS AND CREATE--

DROP TABLE IF EXISTS EMP;

--IDENTITY - AUTOINCREMENTS THE EMPID FIELD--
CREATE TABLE EMP(EmpID INT IDENTITY(1000,1) PRIMARY KEY,
EmpName VARCHAR(50) NOT NULL,
EmpAge INT,
Salary MONEY);

--INSERT VALUES INTO EMP--
INSERT INTO EMP(EmpName,EmpAge,Salary)
VALUES('Obadiah',45,60000),
('Eliud',56,780000),
('Jane',34,340000),
('Jimmy',32,450000),
('Anthoney',38,500000);

--SELECT--
SELECT * FROM EMP;

--ALTER--
ALTER TABLE EMP
ADD Gender VARCHAR(10);

ALTER TABLE EMP
ADD Status VARCHAR(50)
DEFAULT 'Working'
WITH VALUES;

--DROP COLUMNS--
ALTER TABLE EMP DROP COLUMN Gender;

--DELETE--
DELETE FROM EMP
WHERE EmpID=1000;

DELETE TOP(2) FROM EMP
WHERE Salary>=400000;

DELETE TOP(50) PERCENT FROM EMP
WHERE Salary >= 450000;

--UPDATE--
UPDATE EMP
SET Status='Terminated'
WHERE EmpID=1003;