--DROP DATABASE IF EXISTS--
DROP DATABASE IF EXISTS DB;

--CREATE DATABASE--
IF NOT EXISTS (SELECT NAME FROM SYS.DATABASES WHERE NAME = 'DB')
BEGIN
    CREATE DATABASE DB;
END;

--SELECT DATABASE--
USE DB;

--DROP TABLES IF EXISTS--
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Person2;
DROP TABLE IF EXISTS Person3;
DROP TABLE IF EXISTS Person4;

--CREATE TABLES--
CREATE TABLE Person(ID INT NOT NULL PRIMARY KEY,
FName VARCHAR(50) NOT NULL,
LName VARCHAR(50),
Age INT);

CREATE TABLE Person2(ID INT NOT NULL UNIQUE,
FName VARCHAR(50) UNIQUE,
LName VARCHAR(50),
Age INT);

CREATE TABLE Person3(ID INT NOT NULL,
FName VARCHAR(50) NOT NULL,
LName VARCHAR(50) NOT NULL,
Age INT);

CREATE TABLE Person4(ID INT,
FName VARCHAR(50),
LName VARCHAR(50),
Age INT);

--ADD CONSTRAINTS--
--PRIMARY KEY
ALTER TABLE Person3
ADD CONSTRAINT PK_person3 PRIMARY KEY (ID);

--UNIQUE KEY--
ALTER TABLE Person4
ADD CONSTRAINT UNQ_person4 UNIQUE (ID)

--INSERT--
INSERT INTO Person(ID,FName,LName,Age)
VALUES(1,'Amos','Tr',23),
(2,'See','Soon',45),
(3,'Jon','Sin',56),
(4,'Ken','Babu',32),
(5,'Jon','Sin',45);

SELECT * FROM Person2;

INSERT INTO Person2(ID,FName,LName,Age)
VALUES(1,'Amos','Tr',23),
(2,'See','Soon',45),
(3,'Jon','Sin',56),
(4,'Ken','Babu',32),
(5,'Jonn','Sin',45);

INSERT INTO Person3(ID,FName,LName,Age)
VALUES(1,'Amos','Tr',23),
(2,'See','Soon',45),
(3,'Jon','Sin',56),
(4,'Ken','Babu',32),
(5,'Jon','Sin',45);

INSERT INTO Person4(ID,FName,LName,Age)
VALUES(1,'Amos','Tr',23),
(2,'See','Soon',45),
(3,'Jon','Sin',56),
(4,'Ken','Babu',32),
(5,'Jon','Sin',45);

--DELETE ALL RECORDS---
DELETE FROM Person4;

--DROP CONSTRAINTS--
ALTER TABLE Person4
DROP CONSTRAINT UNQ_person4;