--DROP DATABASE--
DROP DATABASE IF EXISTS DB;

--CREATE DATABASE--
IF NOT EXISTS(SELECT NAME FROM SYS.DATABASES WHERE NAME='DB')
BEGIN
	CREATE DATABASE DB;
END;

--USE DATABASE---
USE DB;

--DROP DATABASE--
DROP DATABASE DB;

--CREATE TABLE--
CREATE TABLE Employees(EmpId INT,
EmpName VARCHAR(100),
EmpAge INT,
EmpSalary MONEY);

--SELECT--
SELECT * FROM Employees;

--INSERT--
INSERT INTO Employees(EmpId,EmpName,EmpAge,EmpSalary)
VALUES(1000, 'Julius',35,245000);
INSERT INTO Employees(EmpId,EmpName,EmpAge,EmpSalary)
VALUES(1001, 'Helvine', 30, 123000);

--SELECT A SPECIFIC COLUMN--
SELECT EmpId, EmpName FROM Employees;

--SELECT A SPECIFIC ROW--
SELECT * FROM Employees WHERE EmpId=1000;

--DROP TABLE Employees--
DROP TABLE Employees;
