--DROP DATABASE---
IF EXISTS(SELECT NAME FROM SYS.DATABASES WHERE NAME='StockMS_DB')
BEGIN
	DROP DATABASE StockMS_DB;
END;


--CREATE DATABASE StockMS_DB--
IF NOT EXISTS(SELECT NAME FROM SYS.DATABASES WHERE NAME='StockMS_DB')
BEGIN
	CREATE DATABASE StockMS_DB;
END;

--USE StockMS_DB--
USE StockMS_DB;

--DROP TABLES--
DROP TABLE IF EXISTS Model_Parts;
DROP TABLE IF EXISTS Parts;
DROP TABLE IF EXISTS Brands;
DROP TABLE IF EXISTS Models;
DROP TABLE IF EXISTS Inventories;
DROP TABLE IF EXISTS Invoices;
DROP TABLE IF EXISTS Client_Company;
DROP TABLE IF EXISTS Companies;
DROP TABLE IF EXISTS Inventory_Operations;
DROP TABLE IF EXISTS Repair_Status;
DROP TABLE IF EXISTS Status;
DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS Operations;
DROP TABLE IF EXISTS Repair_Labor;
DROP TABLE IF EXISTS Labors;
DROP TABLE IF EXISTS Repairs;
DROP TABLE IF EXISTS Clients;
DROP TABLE IF EXISTS Users;

--CREATE TABLES---
CREATE TABLE Brands(ID INT IDENTITY(1,1),
Name VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Models(ID INT IDENTITY(100, 1),
Brand_ID INT NOT NULL,
Name VARCHAR(100) NOT NULL,
Image VARBINARY(MAX),
PRIMARY KEY (ID),
FOREIGN KEY (Brand_ID) REFERENCES Brands(ID)
);

CREATE TABLE Parts(ID INT IDENTITY(1000, 1),
Name VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Model_Parts(ID INT IDENTITY(1,1),
Part_ID INT NOT NULL,
Model_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (Part_ID) REFERENCES Parts(ID),
FOREIGN KEY (Model_ID) REFERENCES Models(ID)
);

CREATE TABLE Companies(ID INT IDENTITY(200,1),
Name VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Users(ID INT IDENTITY(10000,1),
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
Password VARCHAR(30) NOT NULL UNIQUE,
PRIMARY KEY (ID)
);

CREATE TABLE Clients(ID INT IDENTITY(1,1),
User_ID INT NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(100) NOT NULL,
Primary_Phone VARCHAR(11) NOT NULL,
Secondary_Phone VARCHAR(11),
PRIMARY KEY (ID),
FOREIGN KEY (User_ID) REFERENCES Users(ID),
);

CREATE TABLE Client_Company(ID INT IDENTITY(1,1),
Client_ID INT NOT NULL,
Company_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (Client_ID) REFERENCES Clients(ID),
FOREIGN KEY (Company_ID) REFERENCES Companies(ID)
);

CREATE TABLE Invoices(ID INT IDENTITY(1,1),
Company_ID INT NOT NULL,
Serial_No INT,
Date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
Total_Value DECIMAL(19,4),
PRIMARY KEY (ID),
FOREIGN KEY (Company_ID) REFERENCES Companies(ID)
);

CREATE TABLE Inventories(ID INT IDENTITY(1,1),
Part_ID INT NOT NULL,
Initial_Qty INT NOT NULL,
Current_Qty INT NOT NULL,
Current_Price DECIMAL(19,2) NOT NULL,
Invoice_ID INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (Part_ID) REFERENCES Parts(ID),
FOREIGN KEY (Invoice_ID) REFERENCES Invoices(ID)
);

CREATE TABLE Operations(ID INT IDENTITY(1,1),
Name VARCHAR(50) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE Repairs(ID INT IDENTITY(1,1),
Client_ID INT NOT NULL,
User_ID INT NOT NULL,
Model_ID INT NOT NULL,
Battery_Sn INT NOT NULL,
Accessories VARCHAR(100) NOT NULL,
Security_Code VARCHAR(30) NOT NULL,
Initial_State VARCHAR(100) NOT NULL,
Client_Defects VARCHAR(100) NOT NULL,
Service_Defects VARCHAR(100) NOT NULL,
Repair_Description VARCHAR(250) NOT NULL,
Service_Notes VARCHAR(200) NOT NULL,
Total DECIMAL(19,2) NOT NULL,
Discount DECIMAL(19,2) DEFAULT (0.00),
Finished VARCHAR(3) NOT NULL,
Created_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
Updated_AT DATETIME NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (Client_ID) REFERENCES Clients(ID),
FOREIGN KEY (User_ID) REFERENCES Users(ID),
FOREIGN KEY (Model_ID) REFERENCES Models(ID)
);

CREATE TABLE Inventory_Operations(ID INT IDENTITY(1,1),
Inventory_ID INT NOT NULL,
Operation_ID INT NOT NULL,
Explanation VARCHAR(150) NOT NULL,
Price DECIMAL(19,2) NOT NULL,
Qty INT NOT NULL,
Repair_ID INT NOT NULL,
Client_ID INT NOT NULL,
User_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (Inventory_ID) REFERENCES Inventories(ID),
FOREIGN KEY (Operation_ID) REFERENCES Operations(ID),
FOREIGN KEY (Repair_ID) REFERENCES Repairs(ID),
FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

CREATE TABLE Messages(ID INT IDENTITY(1,1),
Repair_ID INT NOT NULL,
Type VARCHAR(100) NOT NULL,
Template VARCHAR(100) NOT NULL,
Delivered VARCHAR(3) NOT NULL,
Created_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
Update_AT DATETIME NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (Repair_ID) REFERENCES Repairs(id)
);

CREATE TABLE Labors(ID INT IDENTITY(1,1),
Name VARCHAR(50) NOT NULL,
Price DECIMAL(19,2) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Repair_Labors(ID INT IDENTITY(1,1),
Labor_ID INT NOT NULL,
Repair_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (Labor_ID) REFERENCES Labors(ID),
FOREIGN KEY (Repair_ID) REFERENCES Repairs(ID)
);

CREATE TABLE Status(ID INT IDENTITY(1,1),
Name VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Repair_Statuses(ID INT IDENTITY(1,1),
Repair_ID INT NOT NULL,
Status_ID INT NOT NULL,
Created_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
Updated_AT DATETIME NOT NULL,
User_ID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (Repair_ID) REFERENCES Repairs(ID),
FOREIGN KEY (Status_ID) REFERENCES Status(ID),
FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

--ADD CONSTRAINTS--
ALTER TABLE Clients
ADD CONSTRAINT Client_Email UNIQUE (Email);

ALTER TABLE Clients
ADD CONSTRAINT Client_P_Phone UNIQUE (Primary_Phone);

ALTER TABLE Status
ADD CONSTRAINT Status_Name UNIQUE (Name);

ALTER TABLE Companies
ADD CONSTRAINT Company_Name UNIQUE (Name);

ALTER TABLE Brands
ADD CONSTRAINT Brand_Name UNIQUE (Name);

--INSERT DATA--
INSERT INTO Brands(Name)
VALUES('iPhone'),
('Samsung'),
('Tecno'),
('Sony'),
('Motorora'),
('Nokia'),
('RedMe'),
('Oppo'),
('HP'),
('Lenovo'),
('Amazon'),
('Toshiba');

INSERT INTO Models(Brand_ID,Name, Image)
VALUES(1, 'iPhone Pro 2021', null),
(1, 'iPhone Pro 2021', null),
(3, 'Camon 40', null),
(4, 'Sony xperia', null),
(6, 'Nokia C31', null),
(2, 'Galaxy A56', null),
(6, 'Nokia C31', null),
(9, 'HP Elitebook 840 G3', null),
(9, 'HP Probook 640 G2', null),
(8, 'Reno 12', null),
(1, 'iPhone 2017 Pro', null),
(1, 'iPhone Pro 2020', null);

SELECT * FROM Brands ORDER BY ID ASC;
SELECT * FROM Models ORDER BY ID ASC